Smalltalk current createPackage: 'Flow-Errors' properties: #{}!
Error subclass: #FlowError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #AjaxError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #GettingItemsError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #MissingInstanceVariableReifier
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #MissingItemsError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelCreateError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelDeleteError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelGetterIsMissing
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelMetadataError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelReadError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelRefeshError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

FlowError subclass: #ModelSaveError
	instanceVariableNames: ''
	package: 'Flow-Errors'!

